import { Units } from '../../store/types';
import { unitOptions } from './unitOptions';

export const unitsData: Units = {
  Unit: {
    name: 'Unit',
    type: 'foot',
    points: 0,
    stats: {
      attack: 0,
      move: 0,
      shoot: 0,
      courage: 0,
      armor: 0,
      attackValue: 0,
      defenceValue: 0,
      shootValue: 0,
      shootRange: 0,
      movement: 0,
      strengthPoints: 0,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },
  

  'Mounted men at arms': {
    name: 'Mounted men at arms',
    type: 'Mounted',
    points: 6,
    stats: {
      attack: 5,
      move: 7,
      shoot: 0,
      courage: 3,
      armor: 4,
      attackValue: 3,
      defenceValue: 5,
      shootValue: 0,
      shootRange: 0,
      movement: 10,
      strengthPoints: 6,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Mounted serjants': {
    name: 'Mounted serjants',
    type: 'mounted',
    points: 4,
    stats: {
      attack: 5,
      move: 5,
      shoot: 0,
      courage: 4,
      armor: 3,
      attackValue: 4,
      defenceValue: 5,
      shootValue: 0,
      shootRange: 0,
      movement: 10,
      strengthPoints: 6,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Mounted yeomen': {
    name: 'Mounted yeomen',
    type: 'mounted',
    points: 4,
    stats: {
      attack: 7,
      move: 5,
      shoot: 6,
      courage: 5,
      armor: 3,
      attackValue: 5,
      defenceValue: 6,
      shootValue: 5,
      shootRange: 12,
      movement: 12,
      strengthPoints: 6,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Foot men at arms' {
    name: 'Foot men at arms',
    type: 'foot',
    points: 6,
    stats: {
      attack: 5,
      move: 5,
      shoot: 0,
      courage: 3,
      armor: 4,
      attackValue: 3,
      defenceValue: 4,
      shootValue: 0,
      shootRange: 0,
      movement: 6,
      strengthPoints: 6,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Foot serjants': {
    name: 'Foot serjants',
    type: 'foot',
    points: 4,
    stats: {
      attack: 6,
      move: 5,
      shoot: 0,
      courage: 4,
      armor: 3,
      attackValue: 5,
      defenceValue: 4,
      shootValue: 0,
      shootRange: 0,
      movement: 6
      strengthPoints: 12,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },
  
'Foot yeomen': {
    name: 'Foot yeomen',
    type: 'foot',
    points: 3,
    stats: {
      attack: 6,
      move: 5,
      shoot: 0,
      courage: 4,
      armor: 2,
      attackValue: 5,
      defenceValue: 4,
      shootValue: 0,
      shootRange: 0,
      movement: 8,
      strengthPoints: 12,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Feirce foot': {
    name: 'Feirce foot',
    type: 'foot',
    points: 4,
    stats: {
      attack: 5,
      move: 4,
      shoot: 0,
      courage: 4,
      armor: 2,
      attackValue: 3,
      defenceValue: 6,
      shootValue: 0,
      shootRange: 0,
      movement: 8,
      strengthPoints: 12,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Serfs': {
    name: 'Serfs',
    type: 'foot',
    points: 1,
    stats: {
      attack: 7,
      move: 6,
      shoot: 0,
      courage: 5,
      armor: 1,
      attackValue: 6,
      defenceValue: 6,
      shootValue: 0,
      shootRange: 0,
      movement: 6,
      strengthPoints: 12,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Archers': {
    name: 'Archers',
    type: 'foot',
    points: 4,
    stats: {
      attack: 7,
      move: 6,
      shoot: 6,
      courage: 4,
      armor: 2,
      attackValue: 6,
      defenceValue: 5,
      shootValue: 5,
      shootRange: 18,
      movement: 6,
      strengthPoints: 12,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Crossbowmen': {
    name: 'Crossbowmen',
    type: 'foot',
    points: 4,
    stats: {
      attack: 7,
      move: 6,
      shoot: 7,
      courage: 4,
      armor: 2,
      attackValue: 6,
      defenceValue: 5,
      shootValue: 4,
      shootRange: 18,
      movement: 6,
      strengthPoints: 12,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },

'Bidowers': {
    name: 'Bidowers',
    type: 'foot',
    points: 2,
    stats: {
      attack: 7,
      move: 5,
      shoot: 7,
      courage: 5,
      armor: 1,
      attackValue: 6,
      defenceValue: 6,
      shootValue: 5,
      shootRange: 12,
      movement: 8,
      strengthPoints: 6,
    },
    freeActivations: [],
    rules: [],
    options: {},
    xenosRules: [],
  },
};
